package com.example.riftscompanion.DataBank;

import com.example.riftscompanion.Skill;

import java.util.ArrayList;

public class SkillsData {
    private final ArrayList<Skill> skillsList;
    public ArrayList<Skill> getSkillsList() { return skillsList; }
    public SkillsData() {
        this.skillsList = CreateSkillsList();
    }

    private ArrayList<Skill> CreateSkillsList() {
        /* CREATE ARRAY OF SKILLS */
        ArrayList<Skill> skillsList = new ArrayList<>();

        /*************************************************************************
         All skills initialized here have a skillID value of 0 because it has not
         * yet been assigned in the database. All integer values are also assigned 0
         * if they do not have a value in the rules (e.g. no secondary base proficiency).
         *************************************************************************/

        //region Communications Skills
        skillsList.add(new Skill(0,
                "Cryptography",
                "Skill in recognizing, designing, and cracking secret\n" +
                        "codes and messages. The character must study the code for two\n" +
                        "hours to attempt to break it successfully. A failed roll means the\n" +
                        "individual must study the code for an additional two hours before\n" +
                        "he can try to break it again. The character may attempt to break the\n" +
                        "code sooner, after only 10 minutes of study, but suffers a penalty\n" +
                        "of - 30%.",
                "Communications",
                25,
                5,
                0,
                0,
                "Literacy",
                null,
                0));

        skillsList.add(new Skill(0,
                "Laser",
                "This skill provides the character with an in depth knowledge\n" +
                        "of sophisticated laser communication systems and fiber optic communications.",
                "Communications",
                30,
                5,
                0,
                0,
                "Radio: Basic, Electrical Engineer, Computer Operation",
                null,
                0));

        skillsList.add(new Skill(0,
                "Optic Systems",
                "Provides expert training in the use of special optical\n" +
                        "enhancement equipment such as telescopic lenses, laser targeting,\n" +
                        "thermo-imagers, passive light intensifiers, infrared and ultraviolet\n" +
                        "systems, polarization, light filters, optical scanners, and related devices",
                "Communications",
                30,
                5,
                0,
                0,
                null,
                "T.V./Video",
                5));

        skillsList.add(new Skill(0,
                "Radio: Basic",
                "This is the rudimentary knowledge of the operation and maintenance of field radios and walkie-talkies, wire laying, installation, radio procedure, communication security and visual signs/communications, as well as Morse code. It does not include the ability to make repairs.",
                "Communications",
                45,
                5,
                0,
                0,
                null,
                null,
                0));

        skillsList.add(new Skill(0,
                "Radio: Scramblers",
                "This is training in the use of electronic masking, scrambling and unscrambling equipment, and codes to help foil the detection, interception and interpretation of radio transmissions by the enemy.",
                "Communications",
                35,
                5,
                0,
                0,
                null,
                null,
                0));

        skillsList.add(new Skill(0,
                "Surveillance Systems",
                "This is the study and understanding of the operation, methods, and techniques in the use of surveillance systems. Includes motion detectors, simple and complex alarm systems, audio/visual recording and display equipment, recording methods, amplified sound systems, miniature listening devices (bugs, line tapping), and some optical enhancement systems (specifically as they relate to camera lenses). Tailing, or following someone without their knowledge, is another form of surveillance. This also includes stake-out procedures. A failed surveillance roll indicates that the subject has spotted \"the tail\" and is aware that he is being followed/observed. A failed roll in the use of surveillance equipment means that the equipment does not function as desired, impairing or preventing surveillance; i.e., bug does not transmit, recording garbled, film blurred or fails to record, etc. A failed roll when hiding listening devices means the bug does not function and is easily discovered through the course of casual activity.",
                "Communications",
                30,
                5,
                0,
                0,
                "Electronics: Basic; Electrical Engineering; Computer Operation; Literacy",
                null,
                0));

        skillsList.add(new Skill(0,
                "TV/Video",
                "In-depth training in the use of video and audio recording equipment, filming, editing, dubbing, title making, duplication, and transmission. Includes the use of field equipment; Le., portable video camera and studio equipment.",
                "Communications",
                25,
                4,
                0,
                0,
                null,
                null,
                0));
        //endregion

        //region Cowboy Skills
        skillsList.add(new Skill(0,
                "Branding",
                "",
                "Cowboy",
                50,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Breaking/Taming Wild Horse",
                "",
                "Cowboy",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Herding Cattle",
                "",
                "Cowboy",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Horsemanship: Cowboy",
                "",
                "Cowboy",
                66,
                0,
                55,
                3,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Roping",
                "",
                "Cowboy",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Trick Riding",
                "",
                "Cowboy",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Domestic Skills
        skillsList.add(new Skill(0,
                "Bonsai",
                "",
                "Domestic",
                50,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Brewing",
                "",
                "Domestic",
                25,
                0,
                30,
                5,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Cook",
                "",
                "Domestic",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Corroboree (Australia)",
                "",
                "Domestic",
                30,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Dance",
                "",
                "Domestic",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Fishing",
                "",
                "Domestic",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Floral Arrangement (Ikebana)",
                "",
                "Domestic",
                30,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Gardening",
                "",
                "Domestic",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Go",
                "",
                "Domestic",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Play Musical Instrument",
                "",
                "Domestic",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Poetry (Haiku)",
                "",
                "Domestic",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Recycle",
                "",
                "Domestic",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Rock Painting and Engraving (Australia)",
                "",
                "Domestic",
                36,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Sewing",
                "",
                "Domestic",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Sing",
                "",
                "Domestic",
                35,
                5,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Electrical Skills
        skillsList.add(new Skill(0,
                "Basic Electronics",
                "",
                "Electrical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Computer Repair",
                "",
                "Electrical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Electrical Engineer",
                "",
                "Electrical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Electricity Generation",
                "",
                "Electrical",
                50,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Robot Electronics",
                "",
                "Electrical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Espionage Skills
        skillsList.add(new Skill(0,
                "Detect Ambush",
                "",
                "Espionage",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Detect Concealment",
                "",
                "Espionage",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Disguise",
                "",
                "Espionage",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Escape Artist",
                "",
                "Espionage",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Forgery",
                "",
                "Espionage",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Imitate Voices & Impersonation",
                "",
                "Espionage",
                36,
                0,
                16,
                4,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Intelligence",
                "",
                "Espionage",
                32,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Interrogation Techniques",
                "",
                "Espionage",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Pick Locks",
                "",
                "Espionage",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Pick Pockets",
                "",
                "Espionage",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Snipe",
                "",
                "Espionage",
                0,
                0,
                0,
                0,
                "",
                "+2 to Strike on an aimed shot",
                2));

        skillsList.add(new Skill(0,
                "Tracking (people)",
                "",
                "Espionage",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Wilderness Survival",
                "",
                "Espionage",
                30,
                5,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Horsemanship Skills
        skillsList.add(new Skill(0,
                "Horsemanship: General",
                "",
                "Horsemanship",
                40,
                4,
                20,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Horsemanship: Cowboy",
                "",
                "Horsemanship",
                66,
                3,
                50,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Horsemanship: Knight & Cossack",
                "",
                "Horsemanship",
                40,
                5,
                30,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Horsemanship: Cyber-Knight",
                "",
                "Horsemanship",
                70,
                3,
                50,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Horsemanship: Exotic Animals",
                "",
                "Horsemanship",
                30,
                5,
                20,
                0,
                "",
                null,
                0));
        //endregion

        //region Mechanical Skills
        skillsList.add(new Skill(0,
                "Aircraft Mechanics",
                "",
                "Mechanical Skills",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Armorer/Field Armorer",
                "",
                "Mechanical Skills",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Basic Mechanics",
                "",
                "Mechanical Skills",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Bioware Mechanics",
                "",
                "Mechanical Skills",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Locksmith",
                "",
                "Mechanical Skills",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Mechanical Engineer",
                "",
                "Mechanical Skills",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Robot Mechanics",
                "",
                "Mechanical Skills",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space: Drive Repair",
                "",
                "Mechanical Skills",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space: Satellite Systems",
                "",
                "Mechanical Skills",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Spaceship Mechanics",
                "",
                "Mechanical Skills",
                22,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Submersible Vehicle Mechanics",
                "",
                "Mechanical Skills",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Vehicle Armorer",
                "",
                "Mechanical Skills",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Weapons Engineer",
                "",
                "Mechanical Skills",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        //endregion

        //region Medical Skills
        skillsList.add(new Skill(0,
                "Animal Husbandry",
                "",
                "Medical",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Brewing",
                "",
                "Medical",
                25,
                5,
                30,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Criminal Science & Forensics",
                "",
                "Medical",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Entomological Medicine",
                "",
                "Medical",
                40,
                5,
                20,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Field Surgery",
                "",
                "Medical",
                16,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "First Aid",
                "",
                "Medical",
                45,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Holistic Medicine",
                "",
                "Medical",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Juicer Technology",
                "",
                "Medical",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Paramedic",
                "",
                "Medical",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Medical Doctor",
                "",
                "Medical",
                60,
                5,
                50,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "M.D. in Cybernetics",
                "",
                "Medical",
                40,
                5,
                60,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Pathology",
                "",
                "Medical",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Sea Holistic Medicine",
                "",
                "Medical",
                20,
                5,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Military Skills
        skillsList.add(new Skill(0,
                "Armorer/Field Armorer",
                "",
                "Military",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Camouflage",
                "",
                "Military",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Demolitions",
                "",
                "Military",
                60,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Demolitions Disposal",
                "",
                "Military",
                60,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Demolitions: Underwater",
                "",
                "Military",
                56,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Find Contraband, Weapons & Cybernetics",
                "",
                "Military",
                26,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Military Etiquette",
                "",
                "Military",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Military Fortification",
                "",
                "Military",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Nuclear, Biological & Chemical (NBC) Warfare",
                "",
                "Military",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Parachuting",
                "",
                "Military",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Recognize Weapon Quality",
                "",
                "Military",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Ship to Ship Combat",
                "",
                "Military",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space Defense Systems",
                "",
                "Military",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Trap Construction",
                "",
                "Military",
                20,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Trap/Mine Detection",
                "",
                "Military",
                20,
                5,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Physical Skills
        skillsList.add(new Skill(0,
                "Hand to Hand: Basic",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Expert",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Martial Arts",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Assassin",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Commando",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Aikido (Japan)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Judo (Japan)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Jujitsu (Japan)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Karate (Japan)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Kendo (Japan)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Ninjitsu/Tai-Jutsu (Japan)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Teng-Jutsu (Japan)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hand to Hand: Zanji Shinjinken-Ryu (Japan)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Acrobatics (varies)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Aerobic Athletics",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Athletics (General)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Body Building & Weight Lifting",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Boxing",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Climbing",
                "",
                "Physical",
                40,
                5,
                30,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Deadball",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Gymnastics (varies)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Juicer Football",
                "",
                "Physical",
                32,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Juicer Murderthon",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Prowl",
                "",
                "Physical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Running",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space Combat: Zero Gravity (Basic)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space Combat: Zero Gravity (Advanced)",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space: Depressurization Training",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space: Movement in Zero Gravity",
                "",
                "Physical",
                5,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space: Oxygen Conservation",
                "",
                "Physical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Swimming",
                "",
                "Physical",
                50,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "S.C.U.B.A",
                "",
                "Physical",
                50,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Wrestling",
                "",
                "Physical",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Pilot Skills (Ground, Air, Water)
        skillsList.add(new Skill(0,
                "Advanced Deep Sea Diving",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Airplane",
                "",
                "Pilot (Ground, Air, & Water)",
                50,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Automobile",
                "",
                "Pilot (Ground, Air, & Water)",
                60,
                2,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Bicycling",
                "",
                "Pilot (Ground, Air, & Water)",
                44,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Boat: Motor & Hydrofoil",
                "",
                "Pilot (Ground, Air, & Water)",
                55,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Boat: Sail Type",
                "",
                "Pilot (Ground, Air, & Water)",
                60,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Boat: Ships",
                "",
                "Pilot (Ground, Air, & Water)",
                45,
                5,
                44,
                4,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Boat: Warships & Patrol Boats",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Combat Driving (Special; Australia)",
                "",
                "Pilot (Ground, Air, & Water)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Combat Pod (Special Vehicle)",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Contragravity Pack (Special Vehicle)",
                "",
                "Pilot (Ground, Air, & Water)",
                42,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "EVA",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Flight System Combat (Juicer: Special Vehicle)",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Helicopter",
                "",
                "Pilot (Ground, Air, & Water)",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hover Craft (Ground)",
                "",
                "Pilot (Ground, Air, & Water)",
                50,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hovercycle",
                "",
                "Pilot (Ground, Air, & Water)",
                70,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Jet Aircraft",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Jet Fighters",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Jet Packs",
                "",
                "Pilot (Ground, Air, & Water)",
                42,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Jump Bike Combat (Juicer: Special Vehicle)",
                "",
                "Pilot (Ground, Air, & Water)",
                45,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Kayaking",
                "",
                "Pilot (Ground, Air, & Water)",
                50,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Motorcycle",
                "",
                "Pilot (Ground, Air, & Water)",
                60,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Road Train (Australia)",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Robots & Power Armor",
                "",
                "Pilot (Ground, Air, & Water)",
                56,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Robot Combat: Basic (SPECIAL)",
                "",
                "Pilot (Ground, Air, & Water)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Robot Combat: Elite (SPECIAL)",
                "",
                "Pilot (Ground, Air, & Water)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Spacecraft, Small",
                "",
                "Pilot (Ground, Air, & Water)",
                60,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Spacecraft, General",
                "",
                "Pilot (Ground, Air, & Water)",
                50,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Spacecraft, Advanced",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space Fighter",
                "",
                "Pilot (Ground, Air, & Water)",
                50,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space Yacht",
                "",
                "Pilot (Ground, Air, & Water)",
                44,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Starships",
                "",
                "Pilot (Ground, Air, & Water)",
                36,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Submersibles",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Tracked Vehicles",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Truck",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Tanks & APCs",
                "",
                "Pilot (Ground, Air, & Water)",
                36,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Water Scooters",
                "",
                "Pilot (Ground, Air, & Water)",
                50,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Water Skiing & Surfing",
                "",
                "Pilot (Ground, Air, & Water)",
                40,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Wingrider Flying Wing (Russia)",
                "",
                "Pilot (Ground, Air, & Water)",
                15,
                5,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Pilot Related Skills
        skillsList.add(new Skill(0,
                "Navigation",
                "",
                "Pilot Related",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Navigation: Interplanetary",
                "",
                "Pilot Related",
                45,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Navigation: Orbital",
                "",
                "Pilot Related",
                50,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Navigation: Space",
                "",
                "Pilot Related",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Read & Operate Sensory Equipment",
                "",
                "Pilot Related",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Weapon Systems",
                "",
                "Pilot Related",
                40,
                5,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Rogue Skills
        skillsList.add(new Skill(0,
                "Cardsharp",
                "",
                "Rogue",
                24,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Computer Hacking",
                "",
                "Rogue",
                15,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Concealment",
                "",
                "Rogue",
                20,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Find Contraband, Weapons & Cybernetics",
                "",
                "Rogue",
                26,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Gambling (Standard)",
                "",
                "Rogue",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Gambling (Dirty Tricks)",
                "",
                "Rogue",
                20,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Palming",
                "",
                "Rogue",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Pick Locks",
                "",
                "Rogue",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Pick Pockets",
                "",
                "Rogue",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Prowl",
                "",
                "Rogue",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Safe-Cracking",
                "",
                "Rogue",
                20,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Seduction",
                "",
                "Rogue",
                20,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Streetwise",
                "",
                "Rogue",
                20,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Streetwise: Drugs",
                "",
                "Rogue",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Ventriloquism",
                "",
                "Rogue",
                16,
                4,
                0,
                0,
                "",
                null,
                0));

        //endregion

        //region Science Skills
        skillsList.add(new Skill(0,
                "Anthropology",
                "",
                "Science",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Archaeology",
                "",
                "Science",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Artificial Intelligence",
                "",
                "Science",
                30,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Astrology",
                "",
                "Science",
                8,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Astronomy",
                "",
                "Science",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Biology",
                "",
                "Science",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Botany",
                "",
                "Science",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Chemistry",
                "",
                "Science",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Chemistry: Analytical",
                "",
                "Science",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Marine Biology",
                "",
                "Science",
                35,
                5,
                25,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Mathematics: Basic",
                "",
                "Science",
                45,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Mathematics: Advanced",
                "",
                "Science",
                45,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Oceanographic Surveying",
                "",
                "Science",
                15,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Oxygen Systems",
                "",
                "Science",
                58,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Undersea Farming",
                "",
                "Science",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Xenology",
                "",
                "Science",
                30,
                5,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Technical Skills
        skillsList.add(new Skill(0,
                "Advanced Fishing",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Appraise Goods",
                "A trained eye able to assess the quality and true market value of \"ordinary\" commodities, such as tools, household goods, clothing, furniture, jewelry, gems, art, basic vehicles (hovercycles, cars, motorcycles, bicycles, etc.), common pre-Rifts artifacts (books, films, toys, household goods), land, and similar common trade goods. Does not include military goods (weapons, body armor, power armor, combat vehicles), bionics, technology, magic items, livestock, slaves, or rarities, but may include one of these excluded categories only if the skill is taken twice. The character knows how much he can get by pawning the item as well as what he can sell it for wholesale (to a store/business owner for resale; about 20%-50% of its true value) and retail (open market or retail store; 70-100% of its true value).",
                "Technical",
                30,
                5,
                0,
                0,
                null,
                "+15% to the skill when it is taken twice and add one of the excluded categories.",
                15));

        skillsList.add(new Skill(0,
                "Art",
                "",
                "Technical",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Breed Dogs",
                "",
                "Technical",
                40,
                5,
                20,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Calligraphy",
                "",
                "Technical",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Computer Operation",
                "",
                "Technical",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Computer Programming",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Cyberjacking (Criminals Only)",
                "",
                "Technical",
                50,
                3,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Falconry",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Gemology",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "General Repair & Maintenance",
                "",
                "Technical",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "History",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Jury-Rig",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Language",
                "",
                "Technical",
                50,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Law (General)",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Law (Space; CCW/Phase World)",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Literacy",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Aborigines (Australia)",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Cattle & Animals",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: The Cities (Australia)",
                "",
                "Technical",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: D-Bee",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Demons & Monsters",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Dreamtime Culture (Australia)",
                "",
                "Technical",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Faerie",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Galactic/Alien",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Juicer",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Indians",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Magic",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Psychic & Psionics",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Lore: Religion",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Masonry",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Mining",
                "",
                "Technical",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Mythology",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Photography",
                "",
                "Technical",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Prospecting",
                "",
                "Technical",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Research",
                "",
                "Technical",
                40,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Rope Works",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Salvage",
                "",
                "Technical",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Space Contacts",
                "",
                "Technical",
                6,
                2,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Underseas Salvage",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Whittling & Sculpting",
                "",
                "Technical",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Writing",
                "",
                "Technical",
                25,
                5,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Weapon Proficiencies (Ancient)
        skillsList.add(new Skill(0,
                "W.P. Archery & Targeting",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Battle Axe",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Blunt",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Bola",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Boomerang",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Bow",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Chain",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Crossbow",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Deadball",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Forked",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Grappling Hook",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Knife",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Mouth Weapons",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Net",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Paired Weapons",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Pole Arm",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Shield",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Siege Weapons",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Slingshot",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Small Thrown Weapons",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P.Spear",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Staff",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Sword",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P.Trident",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        skillsList.add(new Skill(0,
                "W.P. Whip",
                "",
                "Weapon Proficiencies (Ancient)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        //endregion

        //region Weapon Proficiencies (Modern)
        skillsList.add(new Skill(0,
                "W.P. Revolver",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Automatic Pistol",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Bolt-Action Rifle",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Automatic and Semiautomatic Rifles",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Submachine-gun",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Flamethrower",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Grenade Launcher",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Harpoon & Spear Gun",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Heavy Weapons",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Torpedo",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Energy Pistol",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Energy Rifle",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Heavy Energy Weapons",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "W.P. Sharpshooting",
                "",
                "Weapon Proficiencies (Modern)",
                0,
                0,
                0,
                0,
                "",
                null,
                0));
        //endregion

        //region Wilderness Skills
        skillsList.add(new Skill(0,
                "Blend",
                "",
                "Wilderness",
                14,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Boat Building",
                "",
                "Wilderness",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Carpentry",
                "",
                "Wilderness",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Dowsing",
                "",
                "Wilderness",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Hunting (SPECIAL)",
                "",
                "Wilderness",
                0,
                0,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Identify Plants & Fruits",
                "",
                "Wilderness",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Outback Survival (Australia)",
                "",
                "Wilderness",
                58,
                2,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Preserve Food",
                "",
                "Wilderness",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Roadwise (Australia)",
                "",
                "Wilderness",
                26,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Skin & Prepare Animal Hides",
                "",
                "Wilderness",
                30,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Spelunking",
                "",
                "Wilderness",
                35,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Track Animals",
                "",
                "Wilderness",
                20,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Track & Hunt Sea Animals",
                "",
                "Wilderness",
                35,
                5,
                25,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Undersea & Sea Survival",
                "",
                "Wilderness",
                25,
                5,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Underwater Navigation",
                "",
                "Wilderness",
                30,
                4,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Use Songlines",
                "",
                "Wilderness",
                20,
                2,
                0,
                0,
                "",
                null,
                0));

        skillsList.add(new Skill(0,
                "Wilderness Survival",
                "",
                "Wilderness",
                30,
                5,
                0,
                0,
                "",
                null,
                0));
        //endregion

        return skillsList;
    }
}
